### ISSUE TITLE
Duplicate folders

### ISSUE THREAD

**Issue by RouvenWulff** [Staubgeborener/klipper-backup#10]
With the first commit, the files and folders are uploaded as expected:

```
Klipper (folder)
--configs (folder)
----klicky.cfg
----macros.cfg
----display.cfg
--KAMP (folder)
----adaptive_meshing.cfg
----adaptive_purging.cfg
printer.cfg
mainsail.cfg
moonraker.conf
sonar.cfg
crownsnest.conf
KAMP_Settings.cfg
```

After a reboot, the folders are duplicated and moved below the original folder. All files are duplicated, too

```
Klipper (folder)
--configs (folder)
----configs (folder)
------klicky.cfg
------macros.cfg
----display.cfg
----klicky.cfg
----macros.cfg
----display.cfg
--KAMP (folder)
----KAMP (folder)
------adaptive_meshing.cfg
------adaptive_purging.cfg
----adaptive_meshing.cfg
----adaptive_purging.cfg
printer.cfg
mainsail.cfg
moonraker.conf
sonar.cfg
crownsnest.conf
KAMP_Settings.cfg
```

This is the .env:

```
github_token=XXX
github_username=XXXX
github_repository=XXX

path_printercfg=/home/pi/printer_data/config/printer.cfg
path_mainsailcfg=/home/pi/mainsail-config/mainsail.cfg
path_moonrakercfg=/home/pi/printer_data/config/moonraker.conf
path_sonarcfg=/home/pi/printer_data/config/sonar.conf
path_crowsnestcfg=/home/pi/printer_data/config/crowsnest.conf
path_kampsettingscfg=/home/pi/printer_data/config/KAMP_Settings.cfg

path_configsfolder=/home/pi/printer_data/config/configs/
path_KAMPfolder=/home/pi/printer_data/config/KAMP/

backup_folder=klipper

```

**Comment by Staubgeborener** [comment]
Just curious - could you please try to start from scratch and remove/comment those two files in your `.env`:

```
#path_configsfolder=/home/pi/printer_data/config/configs/
#path_KAMPfolder=/home/pi/printer_data/config/KAMP/
```

**Comment by RouvenWulff** [comment]
I've commented out the two lines mentioned. After that, I cleared the repo, then:

```
sudo rm -r klipper
sudo rm -r .git
git init
git add .
git commit -m "create repository"
git branch -M main
git remote add origin https://github.com/RouvenWulff/Voron_Config_Backup.git
git push -u origin main
```

The repo showed the .github/workflows folder, as I have not included this in .gitignore. Then I ran

`~/klipper-backup/script.sh`

which then uploaded these files to my repo:
<img width="298" alt="Bildschirmfoto 2023-08-01 um 18 18 32" src="https://github.com/Staubgeborener/klipper-backup/assets/88558070/0e7589dc-4b6d-4d92-a4ac-2592587306ce">

Which is confusing as files are being uploaded that are not specified in the .env config. The script is run via cron on startup and after a reboot, this is what I get:

<img width="289" alt="Bildschirmfoto 2023-08-01 um 18 21 23" src="https://github.com/Staubgeborener/klipper-backup/assets/88558070/ba977799-fef2-4f61-ba17-cf42cc80223e">

**Comment by RouvenWulff** [comment]
Both. I just cleared the repo again and did not restart the printer after the initial commit as the printer is busy atm.

**Comment by rolmos** [comment]
I am in the same situation. All folders are being duplicated and nested into each other.

**Comment by RouvenWulff** [comment]
Seems to work for files at least. I uncommented the two directories to be included in the .env file but those however won't be uploaded to my repo. Here's my .env:

```
github_token=XXX
github_username=XXX
github_repository=XXX

path_printercfg=/home/pi/printer_data/config/printer.cfg
path_mainsailcfg=/home/pi/mainsail-config/mainsail.cfg
path_moonrakercfg=/home/pi/printer_data/config/moonraker.conf
path_sonarcfg=/home/pi/printer_data/config/sonar.conf
path_crowsnestcfg=/home/pi/printer_data/config/crowsnest.conf
path_kampsettingscfg=/home/pi/printer_data/config/KAMP_Settings.cfg

path_configsfolder=/home/pi/printer_data/config/configs/
path_KAMPfolder=/home/pi/printer_data/config/KAMP/

backup_folder=klipper
```

and that is what is being uploaded to the repo:

<img width="365" alt="Bildschirmfoto 2023-08-04 um 10 21 51" src="https://github.com/Staubgeborener/klipper-backup/assets/88558070/8238196d-c057-4214-b082-ea2ca6d520f8">

**Comment by Staubgeborener** [comment]
A quick and dirty workaround could be to delete the backup directory as a final last step. So adding something like this at the very end of `script.sh`:

`rm -r "$parent_path/$backup_folder"`

**Comment by RouvenWulff** [comment]
What would that be good for? Right now the folders specified in the .env will not be uploaded at all...

**Comment by Staubgeborener** [comment]
According to your [post](https://github.com/Staubgeborener/klipper-backup/issues/10#issuecomment-1660687095), the folders will be uploaded (duplicated), if you leave the `cp -r` parameter. The removing part should prevent the duplication.

**Comment by RouvenWulff** [comment]
ok. I put back the `-r` in line 23 and added `rm -r "$parent_path/$backup_folder"`to the end of `script.sh`and if I change any file now, it will not be updated in the repo

**Comment by RouvenWulff** [comment]
I put back in the `-r` in line 23 of `script.sh`and added the line to delete the backup folder to the end of the script. Whilst not ideal, this works for now.
