### ISSUE TITLE
Instructions unclear on correct "full folder" if you're using anything other than a pi

### ISSUE THREAD

**Issue by jonathanalevi** [Staubgeborener/klipper-backup#11]
With so many printers coming with other boards (Fly Gemini, BTT Pi, MKS Makerbase), I think the instructions should be updated with the appropriate directories for those boards. 

Personally, I've been unable to get the backup to work at all for any of my printers... 
<img width="740" alt="Screen Shot_2023-08-01 13 42 22_ONaiyZ" src="https://github.com/Staubgeborener/klipper-backup/assets/1540530/572d8a8f-6cb4-4296-bad6-b8f556499124">

**Comment by Staubgeborener** [comment]
> With so many printers coming with other boards (Fly Gemini, BTT Pi, MKS Makerbase), I think the instructions should be updated with the appropriate directories for those boards.

There are too many boards and i mean, everyone can pick out their paths for themselves.

> Personally, I've been unable to get the backup to work at all for any of my printers...

Please post your `script.sh` and also your `.env` (without token and any other credentials).

**Comment by scarteo** [comment]
you need to add "-r" behind cp in your script.sh file 
like this
`# Copy important files into backup folder
while read -r path; do
  file=$(basename "$path")
  cp -r "$path" "$parent_path/$backup_folder/$file"
done < <(grep 'path_' "$parent_path"/.env | sed 's/^.*=//')
`
