### ISSUE TITLE
Filewatch needs to pass `-c` switch to script.sh to function as intended.

### ISSUE THREAD

**Issue by crkochan** [Staubgeborener/klipper-backup#115]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the `code` more readable which helps to fix the problem and that I have tested the `--fix` command mentioned above without success.

### What happened

On a fresh install with automated backups enabled, changes to watched files would not result in a commit/push.

https://github.com/Staubgeborener/klipper-backup/blob/260b84f38225fb25f81c2c2689319dd7a760459c/utils/filewatch.sh#L28

I removed the `> /dev/null 2>&1` portion of the backup command so I could get an idea of what the problem was in journalctl.

```
Aug 08 19:13:35 kosh env[31539]: Setting up watches.  Beware: since -r was given, this may take a while!
Aug 08 19:13:35 kosh env[31539]: Watches established.
Aug 08 19:14:04 kosh env[31540]: Event Type: MOVED_TO, Watched Path: /home/pi/printer_data/config/user-macros/, File Name: customize-start_print.cfg
Aug 08 19:14:04 kosh env[31553]: [42B blob data]
Aug 08 19:14:04 kosh env[31549]: [49B blob data]
Aug 08 19:14:04 kosh env[31549]: [81B blob data]
Aug 08 19:14:04 kosh env[31549]: Usage: script.sh [OPTION]...
Aug 08 19:14:04 kosh env[31549]: Klipper-Backup is a script for manual or automated Klipper GitHub backups. It's Lightweight, pragmatic and comfortable.
Aug 08 19:14:04 kosh env[31549]: https://github.com/Staubgeborener/klipper-backup
Aug 08 19:14:04 kosh env[31549]: https://klipperbackup.xyz
Aug 08 19:14:04 kosh env[31549]: Options:
Aug 08 19:14:04 kosh env[31549]:   -h, --help                     display this help and exit
Aug 08 19:14:04 kosh env[31549]:   -c, --commit_message [TEXT]    use your own commit message for the git push
Aug 08 19:14:04 kosh env[31549]:   -f, --fix                      delete the config_backup folder. This can help to solve the vast majority of error messages
Aug 08 19:14:04 kosh env[31549]: Examples:
Aug 08 19:14:04 kosh env[31549]:   script.sh --help
Aug 08 19:14:04 kosh env[31549]:   script.sh --commit_message "My own commit message"
Aug 08 19:14:04 kosh env[31549]:   script.sh --fix
```

Adding in `-c` in the proper place caused the automated process to function as expected.

### What did you expect to happen

Out of the box automated backups to appear in GitHub when a file is altered in `printer_data/config`.

### How to reproduce

1. Properly setup klipper-backup, and confirm with a manual backup operation.
2. Install the filewatch backup service via `install.sh` when prompted.
3. Change a watched file under `printer_data/config`
4. Observe no new commit in GitHub.

### Additional information

I would also advocate for keeping `> /dev/null 2>&1` out of the service unit file so that errors such as this can be more easily discovered in journalctl.

**Comment by Staubgeborener** [comment]
Thanks for pointing this out, hopefully the error has been corrected with [this PR](https://github.com/Staubgeborener/klipper-backup/pull/116). You are welcome to give feedback [here](https://github.com/Staubgeborener/klipper-backup/issues/114) that everything works or that something is still wrong.
