### ISSUE TITLE
install.sh overwrites git clone

### ISSUE THREAD

**Issue by scarteo** [Staubgeborener/klipper-backup#12]
`git clone https://github.com/Staubgeborener/klipper-backup klipper-backup-main
chmod +x ./klipper-backup-main/*.sh && ./klipper-backup-main/install.sh`

this installs the older code in the release. 
example without the "cp -r" in the backup script

**Comment by Staubgeborener** [comment]
My mistake, fix'd that with a [new release](https://github.com/Staubgeborener/klipper-backup/releases/tag/0.3.5).
