### ISSUE TITLE
I tottaly screwed up the insttalation procces. How can i uninstall the program?

### ISSUE THREAD

**Issue by SejeAnd** [Staubgeborener/klipper-backup#13]

**Comment by Staubgeborener** [comment]
I don't know in which step you screwed up, but there is nothing like "deinstallation". Just remove the `klipper-backup` folder (or whatever this is called on your system). It's a simple script which lays around on your system and is waiting to be runned.

Login via ssh and do:
1. `cd ~ && ls -l` you should now see your `klipper-backup` folder (maybe it's called `klipper-backup-main`? Like i said, i don't which step you screwed up or if you renamed the folder).

2. Remove the folder `rm -r klipper-backup`. That's pretty much it.

If you edit your `moonraker.conf` file just remove the [entry](https://github.com/Staubgeborener/klipper-backup/wiki/Installation%3A-Moonraker-Support).

**Comment by Staubgeborener** [comment]
I close this one, as this is not a real issue.
