### ISSUE TITLE
Unable to backup to github

### ISSUE THREAD

**Issue by drumstick77** [Staubgeborener/Klipper-Backup#130]
Hi,

I've re-installed  using install.sh and entered in all of my details but it's not backing up to my github. it's not happening on both printers. please let me know what you need from me in order to help with the troubleshooting. cheers.

**Comment by Staubgeborener** [comment]
Please open a new issue and use the [bug report](https://github.com/Staubgeborener/Klipper-Backup/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) this time, as it may contain important information.
