### ISSUE TITLE
it's not backing up

### ISSUE THREAD

**Issue by drumstick77** [Staubgeborener/Klipper-Backup#131]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the code more readable which helps to fix the problem and that I have tested the --fix command mentioned above without success.

### What happened

I've reinstalled and followed install.sh, entered my details but it's not backing up. it's now doing it on both printers. 

### What did you expect to happen

I expected it to backup to my github

### How to reproduce

 I've re-installed but it is still not uploading files to my repositories

### Debug

```shell
Unable to create/upload debug
```

### Additional information

![image](https://github.com/user-attachments/assets/266eb7f5-024f-4439-ba5c-8849883373a6)

**Comment by Staubgeborener** [comment]
> Unable to create/upload debug

 Why?

I think you are using your github password in your .env file instead a [token](https://klipperbackup.xyz/installation/#create-github-token). The error message tells you basically [this](https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls). 
> Password-based authentication for Git has been removed in favor of more secure authentication methods. For more information, see "[Managing your personal access tokens]:

**Comment by drumstick77** [comment]
okay, so how would one resolve this issue?

**Comment by Staubgeborener** [comment]
You create a token like it is explained [here](https://klipperbackup.xyz/installation/#create-github-token) and use it instead your github password in your .env. You could simple run the `install.sh` and add the token if the installer ask for it.

**Comment by drumstick77** [comment]
ok, yes that's exactly how I did it
I created the token in github and pasted it during the wizard of running install.sh

**Comment by drumstick77** [comment]
I never had to edit or tweak .env

**Comment by drumstick77** [comment]
should I remove the current .env and start again?

**Comment by Staubgeborener** [comment]
You can just edit your post instead of re-posting.

> should I be generating tokens (classic)? or fine-grained tokens? because your instruction says doesn't matter which one. and I'm using fine-grained tokens

Indeed, it doesn't matter but just create a Fine-grained token with these settings (i will update the docs with this information):
```
Only select repositories -> select your backup repository

Account permissions:
-------------------------------
Administration: Read and write
Commit statuses: Read and write 
```

> should I remove the current .env and start again?
This is not necessary. Create the token like i explained, run the `install.sh` again (like `~/klipper-backup/install.sh`) and add the token when the script ask for it.

If this still doesn't work, please give me the whole `script.sh --debug` output.

**Comment by drumstick77** [comment]
ok, I've managed to fix this. I went with the classic token which gives the ability to set permission like per modbot video. the fine grain is slightly different. Although, if I remember rightly Minimal 3DP went with fine grain and he clicked on generate token without setting any permissions. Anyway, I will go with this classic token and will also apply to my other printers. thanks for you help.

**Comment by drumstick77** [comment]
just did it do another printer and was getting this error 
![image](https://github.com/user-attachments/assets/2ccc625f-6699-4097-86fb-60b73d651b3d)

**Comment by Staubgeborener** [comment]
Try `script.sh --fix` and run again.

**Comment by drumstick77** [comment]
Good man! awesome. thank you. all sorted now. Cheers
