### ISSUE TITLE
Installation Guide Missing Permission Requirement for Effective Push

### ISSUE THREAD

**Issue by Navist** [Staubgeborener/Klipper-Backup#132]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the code more readable which helps to fix the problem and that I have tested the --fix command mentioned above without success.

### What happened

Without "Contents" Read and write permission you won't be able to push to git through fine-grained access token.

### What did you expect to happen

The installation guide to provide proper guidance.

### How to reproduce

Enable only the permissions stated in the installation guide.

"Repository permissions:
Administration: Read and write
Commit statuses: Read and write"

### Debug

```shell
None
```

**Comment by Tylerjet** [comment]
Updated the docs with the correct fine grained perms.
