### ISSUE TITLE
Im trying to install the program with my own fork because the update manager states "Dirty". I have tried installing the program several times, but im always getting this error in the Initialization step:

### ISSUE THREAD

**Issue by SejeAnd** [Staubgeborener/klipper-backup#14]
pi@vyper:~/klipper-backup $ cd ~/klipper-backup
sudo rm -r .git
git init
git add .
git commit -m "create repository"
git branch -M main
git remote add origin https://github.com/SejeAnd/Vyper.git
git push -u origin main
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /home/pi/klipper-backup/.git/
warning: adding embedded git repository: klipper-backup
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint:
hint:   git submodule add <url> klipper-backup
hint:
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint:
hint:   git rm --cached klipper-backup
hint:
hint: See "git help submodule" for more information.
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'pi@vyper.(none)')
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/SejeAnd/Vyper.git'

**Comment by Staubgeborener** [comment]
The dirty flag error has its own open [issue](https://github.com/Staubgeborener/klipper-backup/issues/6), the reason for this error is explained in [this](https://github.com/Staubgeborener/klipper-backup/issues/4#issuecomment-1590680600) post.

Btw your posts are hard to read, you can use [markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to make it easier for all of us, for example with \`code\` you create create `code` or with

\```shell
[user@system~]$ echo some shell stuff with more lines
some shell stuff with more lines
\```

you create

```shell
[user@system~]$ echo some shell stuff with more lines
some shell stuff with more lines
```

Also, i would say, always post screenshots from your terminal.

Like i said at the beginning: Dirty flag issue is a known issue, and we have an open issue just for this problem, so i will close this one here for the overview.
