### ISSUE TITLE
"corrupt" error

### ISSUE THREAD

**Issue by fushiV** [Staubgeborener/klipper-backup#15]
I cant seem to figure out whats causing this "corrupt" error, when I click hard recovery it shows a user name error but my user name is correct in the .env and my files back up just fine. I have tried reinstalling everything from scratch but no change. I also get this other warning while using the backup script from ssh, not sure its related. I also can't figure out why my two of my .cfg don't show up in GitHub with the actual contents but instead just show the file path also pictured below.

<img width="589" alt="Screenshot 2023-10-05 at 08 02 47" src="https://github.com/Staubgeborener/klipper-backup/assets/144940481/3efa93f7-c87e-47d2-9fa8-96d7bde8c10f">
<img width="577" alt="Screenshot 2023-10-05 at 07 46 29" src="https://github.com/Staubgeborener/klipper-backup/assets/144940481/2fc3adbb-0ac2-42fc-ad21-933bedb39acb">
<img width="663" alt="Screenshot 2023-10-05 at 07 44 57" src="https://github.com/Staubgeborener/klipper-backup/assets/144940481/59855601-15eb-4a03-ad5a-f14bc883be82">
<img width="430" alt="Screenshot 2023-10-05 at 07 45 09" src="https://github.com/Staubgeborener/klipper-backup/assets/144940481/068e4daf-c073-49c5-8a00-8a5d4e081a51">
<img width="606" alt="Screenshot 2023-10-05 at 07 45 46" src="https://github.com/Staubgeborener/klipper-backup/assets/144940481/ff2c1576-3d6a-4ded-b88f-8764cdda3a40">

**Comment by fushiV** [comment]
Thank you for the quick reply. Please see the below picture and text of my .env I have tried to keep it simple and just back up the entire printer_data on this install, but previously I had it set to back up each individual cfg file and it had the same problem for the mainsail.cfg (i did not think to look at the timelapse.cfg during the first install).


.env:
---------------
github_token=github_pat_xxxxxxxxxxxxxxxxxx
github_username=fushiv
github_repository=V2-1-backup


#back up whole folder syntax:
path_klipperdata=/home/pi/printer_data/

backup_folder=V2-1_klipper_backup
---------------

<img width="768" alt="Screenshot 2023-10-05 at 11 33 07" src="https://github.com/Staubgeborener/klipper-backup/assets/144940481/82cb2f84-607e-4dfd-a077-9c0b3dc5f62a">

**Comment by Staubgeborener** [comment]
Which version of klipper-backup do you use? `cat version`
