### ISSUE TITLE
Incremental local copy with rsync

### ISSUE THREAD

**Issue by Tarakesh83** [Staubgeborener/klipper-backup#19]
Script uses cp -r to copy files to the git directory.
This always copies all files and overwrites existing ones instead of just the changed ones adding unneeded wear to sd-cards
instead rsync -a should be used.
This only copies actually changed/new files.
If one wants to be paranoid rsync -a --checksum could be used so every file is actually checkum compared.

**Comment by Staubgeborener** [comment]
Thanks for the hint, I will think about it and maybe patch it in the next weeks
