### ISSUE TITLE
commenting out paths in .env not working

### ISSUE THREAD

**Issue by cherub-i** [Staubgeborener/klipper-backup#20]
`script.sh` is also working on pathes in `.env`, which are commented out with a `#`.
I would prefer to be able to comment out lines by adding a `#` at the beginning.

I believe, you could achieve this by changing `script.sh:24` to
```bash
done < <(grep -v '^#' "$parent_path"/.env | grep 'path_' | sed 's/^.*=//')
```

**Comment by cherub-i** [comment]
Sorry - typically German, pointing out something small could be changed, but forgetting the main thing:
Thank you for providing this script. I find it really helpful :-)

**Comment by Staubgeborener** [comment]
Good idea, I close this one as you already open a pull request. Thanks!
