### ISSUE TITLE
One slight wiki adjustment i noticed was incorrect

### ISSUE THREAD

**Issue by Tylerjet** [Staubgeborener/klipper-backup#25]
@Staubgeborener 
on this page: https://github.com/Staubgeborener/klipper-backup/wiki/Installation%3A-Configuration#env:~:text=You%20could%20also%20use%20backup_folder%3D.%20for%20example

The line: You could also use `backup_folder=.` for example

The code block should be `backup_folder=config_backup` as that is the root of the backup repository, using `backup_folder=.` would make the script create the files directly in the users home directory `/home/{username}` which we don't want to happen as then their entire home directly will become a git repo hehe.

Which now gives me an idea of placing in a function to check if that variable does equal . so that it can warn the users. Will look into that maybe later this week when work is less hectic.

**Comment by Staubgeborener** [comment]
Thanks for the hint. I completely removed the line. Also, I changed the moonraker conf in the [tldr](https://github.com/Staubgeborener/klipper-backup/wiki/tldr) section since `is_system_service:` is deprecated in the [future](https://github.com/Arksine/moonraker/blob/master/docs/configuration.md).
