### ISSUE TITLE
Unclear, what that means and what to do 

### ISSUE THREAD

**Issue by Sonnenwerk** [Staubgeborener/klipper-backup#31]
1. "The branch name defined in .env does not match the branch that is currently checked out, to remove this warning update branch_name in .env to" --> i have the branch "main" in git and the .env  "branch_name=mainbranch_name=main". I also tried "head", but that did not help

2. Von https://github.com/Experiment4/Evolux
 * branch            HEAD       -> FETCH_HEAD
fatal: Es sieht so aus, als ob es das Verzeichnis rebase-merge bereits gibt
und es könnte ein anderer Rebase im Gange sein. Wenn das der Fall ist,
probieren Sie bitte
        git rebase (--continue | --abort | --skip)
Wenn das nicht der Fall ist, probieren Sie bitte
        rm -fr ".git/rebase-merge"
und führen Sie diesen Befehl nochmal aus. Es wird angehalten, falls noch
etwas Schützenswertes vorhanden ist.

fatal: ungültige Refspec ''
 
--> wie bekomme ich diese Meldung weg, bzw. so hin, dass das backup richtig läuft ?

**Comment by Sonnenwerk** [comment]
Yes, i had "main" first. As this did not work, i tried "head". Neither worked.

**Comment by Staubgeborener** [comment]
Well, you wrote `branch_name=mainbranch_name=main` and not `branch_name=main`. 

But if you're 100% sure it's correct inside `.env`: You screwed something up. At this point i am talking about [release 1.1.0](https://github.com/Staubgeborener/klipper-backup/releases/tag/1.1.0):

You could try to move into your backup folder which should be `cd ~/config_backup` and do a `git rebase --continue` or `git rebase --abort` there and run the `script.sh` again.

**Comment by Sonnenwerk** [comment]
Yes, this part, but now i have something like this. 
I am not sure yet, how i can clean up all this (mess).
Would like to del my github backup and start the first backup from scratch...

 
"  18-01-24), es sollte vielleicht nach home/tom/printer_data/config/printer_data/config/crowsnest.conf verschoben werden.
KONFLIKT (Speicherort): klipper/printer_data/config/.moonraker.conf.bkp hinzugefügt in HEAD innerhalb eines Verzeichnisses, das umbenannt wurde in 74fef7e (New backup                                                                                   from 18-01-24), es sollte vielleicht nach home/tom/printer_data/config/printer_data/config/.moonraker.conf.bkp verschoben werden.
KONFLIKT (Speicherort): klipper/printer_data/comms/klippy.serial hinzugefügt in HEAD innerhalb eines Verzeichnisses, das umbenannt wurde in 74fef7e (New backup from 1                                                                                  8-01-24), es sollte vielleicht nach home/tom/printer_data/config/printer_data/comms/klippy.serial verschoben werden.
KONFLIKT (Speicherort): klipper/printer_data/backup/20231204T185009Z/config/moonraker.conf hinzugefügt in HEAD innerhalb eines Verzeichnisses, das umbenannt wurde in                                                                                   74fef7e (New backup from 18-01-24), es sollte vielleicht nach home/tom/printer_data/config/printer_data/backup/20231204T185009Z/config/moonraker.conf verschoben werde                                                                                  n.
KONFLIKT (Speicherort): klipper/printer_data/.moonraker.uuid hinzugefügt in HEAD innerhalb eines Verzeichnisses, das umbenannt wurde in 74fef7e (New backup from 18-01                                                                                  -24), es sollte vielleicht nach home/tom/printer_data/config/printer_data/.moonraker.uuid verschoben werden.
error: Konnte 74fef7e... (New backup from 18-01-24) nicht anwenden
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Konnte 74fef7e... (New backup from 18-01-24) nicht anwenden
To https://github.com/Experiment4/Evolux.git
 ! [rejected]        main -> main (non-fast-forward)
error: Fehler beim Versenden einiger Referenzen nach 'https://github.com/Experiment4/Evolux.git'
Hinweis: Aktualisierungen wurden zurückgewiesen, weil die Spitze eines versendeten
Hinweis: Branches hinter seinem externen Gegenstück zurückgefallen ist. Checken Sie
Hinweis: diesen Branch aus und führen Sie die externen Änderungen zusammen
Hinweis: (z. B. 'git pull ...') bevor Sie erneut "push" ausführen.
Hinweis: Siehe auch die Sektion 'Note about fast-forwards' in 'git push --help'
Hinweis: für weitere Details.

**Comment by Sonnenwerk** [comment]
Thanks for supporting here !

**Comment by Staubgeborener** [comment]
Alright, glad you solve it.
