### ISSUE TITLE
Suggestion for the Q&A

### ISSUE THREAD

**Issue by Duffy77** [Staubgeborener/klipper-backup#38]
Hi, thanks for this great script.
I have been playing around with it and was wondering how to secure the mainsail folders for myself.
In the Q&A only subfolders are mentioned.
But this works for every folder (maybe only inside home folder?)
So my suggestion would be to adjust the Q&A accordingly so that it is more obvious that other folders can also be backed up. And not only subfolders

**Comment by Staubgeborener** [comment]
Hey, thanks for the request. The Q&A section is not up-to-date as the code has changed several times. On the long run, i want to replace the GitHub wiki with a "real" wiki site which is deployed by MkDocs.

Benefits for users:
- better overview
- more formatting options
- users can create PRs to actively contribute to the wiki themselves

At the same time, the wiki will be revised accordingly. When the time comes, I'll be happy to ping you.
