### ISSUE TITLE
Individual commit message with "Klipper Macro"

### ISSUE THREAD

**Issue by Duffy77** [Staubgeborener/klipper-backup#41]
**Did you read the wiki?**
- [x ] Yes
- [ ] No

**Describe the bug**
I have created a klipper macro with a parameter. The side from gcode_shell_command is working and they are passing the arguments with an array to the called bash script.
So i created a github issue https://github.com/dw-0/kiauh/issues/425

I think when you change your lines 
```
if [ -n "$1" ]; then
    commit_message="$1"
```
to
```
if [ -n "$1" ]; then
    commit_message="$@"
``` 

what do you think about 

**Informationen**
Use [markdown syntax ](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#styling-text), like `backticks`.
Please post the entire output from your terminal that is related to the bug, and remember to censor your token.

**To Reproduce**
Steps to reproduce the behavior. Really, step by step. How you downloaded the script, how you installed it, how and when do you edit the `.env` file, mention whether this file was subsequently changed again, etc. Step by step:

Steps are mentioned in https://github.com/dw-0/kiauh/issues/425
The screenshot with the macro is a little bit wrong and the parameter should be placed within quotation marks.
But then only the first word is the commit message.

**Screenshots**

**Additional context**

**Comment by Staubgeborener** [comment]
Thanks for the idea, I have tested it and found it to be a good idea. It is now included in the script.
