### ISSUE TITLE
[Feature request]:  Can Add something in the Automated Backups Doc?

### ISSUE THREAD

**Issue by GHTGXL** [Staubgeborener/klipper-backup#48]
### Is your feature request related to a problem? Please describe.

Because I'm using CB1, the link is not /home/mks/klipper-backup/script.sh, it is /home/biqu/klipper-backup/script.sh, and the user is also different, is not root, is biqu.

### Describe the solution you'd like

So can add the warning about the different link and the username?

### Describe alternatives you've considered

Or another way to remind you about these two?

**Comment by Staubgeborener** [comment]
Are we talking about the [systemd service file](https://staubgeborener.github.io/klipper-backup/)?

**Comment by Tylerjet** [comment]
Will be updated in the docs please change ExecStart line in the service to:

```ExecStart=/bin/bash -c 'bash $HOME/klipper-backup/script.sh "New Backup on boot $(date +%%D)"'```

**Comment by Staubgeborener** [comment]
The docs are updated now
