### ISSUE TITLE
cp: unrecognized option '--parents'

### ISSUE THREAD

**Issue by skabashnyuk** [Staubgeborener/klipper-backup#74]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the `code` more readable which helps to fix the problem

### What happened

Error 
```
cp: unrecognized option '--parents'
BusyBox v1.36.1 (2024-02-24 17:59:02 UTC) multi-call binary.

Usage: cp [-arPLHpfinlsTu] SOURCE DEST
or: cp [-arPLHpfinlsu] SOURCE... { -t DIRECTORY | DIRECTORY }

Copy SOURCEs to DEST

	-a	Same as -dpR
	-R,-r	Recurse
	-d,-P	Preserve symlinks (default if -R)
	-L	Follow all symlinks
	-H	Follow symlinks on command line
	-p	Preserve file attributes if possible
	-f	Overwrite
	-i	Prompt before overwrite
	-n	Don't overwrite
	-l,-s	Create (sym)links
	-T	Refuse to copy if DEST is a directory
	-t DIR	Copy all SOURCEs into DIR
	-u	Copy only newer files
```

during execution of `./klipper-backup/script.sh` script

### What did you expect to happen

Successful backup.

### How to reproduce

- Printer Ender 3 V3 KE.
- Install bash `GNU bash, version 5.2.15(1)-release (mipsel-openwrt-linux-gnu)`.  installed from https://github.com/Entware/Entware repository
- `BusyBox v1.36.1 (2024-02-24 17:59:02 UTC) multi-call binary.` installed from https://github.com/Entware/Entware repository
- add soft link `ln -s /usr/data/printer_data/ /root/printer_data`
- Executed backup script

**Comment by Staubgeborener** [comment]
Is busybox / entware even handling the `--parents` parameter in `cp` command? I mean, I think macOS systems (and other BSD systems?) also have problems using `cp --parents`. I think `--parents` only works on non-POSIX systems but not sure.

Could you try to replace the `cp -r --parents "$file" "$backup_path/"` code in [line 105](https://github.com/Staubgeborener/klipper-backup/blob/7880242865f827b1971c0a1f52dd018c7fd8f4b9/script.sh#L105) with the following:
`rsync -R "$file" "$backup_path/"`

Please tell me if this works and i will create an update for this behaviour.

**Comment by Tylerjet** [comment]
pr made 👍

**Comment by Staubgeborener** [comment]
Good. Could you do me a favor and replace this new line now with this here

```shell

if ! cp --parents "$file" "$backup_path/"; then
    rsynch -R "$file" "$backup_path/"
fi
```

Does this also work?

**Comment by Staubgeborener** [comment]
There is a new [update](https://github.com/Staubgeborener/klipper-backup/pull/76) available with this fix.
