### ISSUE TITLE
Feature request: incremental backups

### ISSUE THREAD

**Issue by mrodyhin** [Staubgeborener/klipper-backup#8]
It would be nice not to reinit whole repo all the time, and push only things that was changed. That is git natural behaviour, and that will allow to look through the history of the changes over time, which could be really helpful.

**Comment by Staubgeborener** [comment]
> and push only things that was changed

> that will allow to look through the history of the changes over time

Are we talking about the same issue [here](https://github.com/Staubgeborener/klipper-backup/issues/9)?

**Comment by mrodyhin** [comment]
it starts working after full reinstall, so closing this issue.
