### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 3DeezNutz** [Staubgeborener/klipper-backup#83]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the `code` more readable which helps to fix the problem

### What happened

I tried updating and im getting this error. 
![image](https://github.com/Staubgeborener/klipper-backup/assets/154413625/3a66aeb3-b444-45c6-831a-4ea89fb2d94e)

### What did you expect to happen

just to update my back up files.

### How to reproduce

just hit the gitupdate macro.

### Additional information

![image](https://github.com/Staubgeborener/klipper-backup/assets/154413625/188957ac-38ff-4d9e-b666-361f69a49475)

**Comment by Tylerjet** [comment]
I had this happen but not really sure why it occurs what you can try is going into the config_backup folder via ssh and running `git pull` and i believe that should be able to un corrupt the repo

**Comment by 3DeezNutz** [comment]
What do you mean by git pull? I’m not very good at this.

**Comment by Tylerjet** [comment]
git pull is a command, once logged into the PC running klipper you will want to do:
```
cd config_backup
```
and then ```
git pull
```

and see what errors occur if any

**Comment by 3DeezNutz** [comment]
![image](https://github.com/Staubgeborener/klipper-backup/assets/154413625/41e408da-62f4-433a-bcdd-2d11191aa330)

like this?

**Comment by Tylerjet** [comment]
yep ok so try this instead
```
git init
```
and then 
```
git pull
```

**Comment by 3DeezNutz** [comment]
![image](https://github.com/Staubgeborener/klipper-backup/assets/154413625/e86ffdfc-b700-4b4e-a9d1-e6f1d197e5cb)

**Comment by 3DeezNutz** [comment]
![image](https://github.com/Staubgeborener/klipper-backup/assets/154413625/5dae8bad-35e9-46f8-896c-faedd01f939d)

**Comment by Tylerjet** [comment]
could you try a ```git pull``` again what shows up

**Comment by 3DeezNutz** [comment]
ok thank you that fixed it

**Comment by 3DeezNutz** [comment]
how would i go about backing up my history on mainsail?

**Comment by Tylerjet** [comment]
Not sure what you mean are you referring to the the mainsail.cfg file? that is a read only file and can't be modified in the editor so it is skipped from backups.

**Comment by 3DeezNutz** [comment]
like all the data from your total print hours. 
![image](https://github.com/Staubgeborener/klipper-backup/assets/154413625/ea4d9c31-cf0b-4e37-9172-7bee3e468631)

**Comment by Tylerjet** [comment]
That data is saved in a database specific to moonraker and has a bit more involved process to backup the data base to be able to restore it if needed later.

**Comment by 3DeezNutz** [comment]
Could this be a future request feature?

**Comment by Staubgeborener** [comment]
Maybe, it's possible to [backup and restore](https://moonraker.readthedocs.io/en/latest/installation/#lmdb-database-backup-and-restore) the moonraker database. We could add a simple `~/moonraker/scripts/backup-database.sh -o ~/moonraker-database.backup` command line in future ([code](https://github.com/Arksine/moonraker/blob/master/scripts/backup-database.sh)) which can be toggled with a `backup_database` parameter (or something like that) in future.
Right now you can backup this database by yourself and add the path to the `data.mdb` file in your `.env`.

**Comment by 3DeezNutz** [comment]
Do I use single file?

**Comment by Staubgeborener** [comment]
What.

**Comment by 3DeezNutz** [comment]
do i use this 
![image](https://github.com/Staubgeborener/klipper-backup/assets/154413625/f4b14d36-5213-4b97-b20b-747fb3dea19f)

**Comment by Staubgeborener** [comment]
Yes. If you run the backup like this
`~/moonraker/scripts/backup-database.sh -o ~/moonraker-database.backup`
You create the backup file of your database in your home directory. 

So basically adding something like this in your `.env` is enough:
`path_moonrakerdatabase=moonraker-database.backup`

**Comment by Staubgeborener** [comment]
Yes. If you run the backup like this
`~/moonraker/scripts/backup-database.sh -o ~/moonraker-database.backup`
You create the backup file of your database in your home directory. 

So basically adding something like this in your `.env` is enough:
`path_moonrakerdatabase=moonraker-database.backup`

I would suggest to create the database backup in a extra directory and not in your home directory. After pushing all files to GitHub so you avoid disorganization in your repository.
