### ISSUE TITLE
Created two users?

### ISSUE THREAD

**Issue by Tmallard** [Staubgeborener/klipper-backup#86]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the `code` more readable which helps to fix the problem

### What happened

Installed this excellent script on two of my other printers and it works great. When it came to the third was was going faster than a beginner should. I now how two users? "Pi" and "Password" (my password for the pi username. 

I discovered this when I first tried to upload the scrips to GIT. But I could not see the usual folders when using "LS". Today I logged in via Win SCP and found in the "Home" Folder two users "Pi" and "Password" 

Did I accidently give the script my password instead of my user name and it moved files around? It seems like I might have to reinstall and start clean here. 

### What did you expect to happen

Created additional script files under the Pi username

I thought the issue was that I hit a wrong key trying to save in Nano and it gave me an error that another user was editing the .ENV file when I opened it back up. 

Sorry for the beginner mistake........ 

### How to reproduce

I'm not sure.

**Comment by Staubgeborener** [comment]
So to summarize: you did something wrong and now you have two folders in home which are called pi and your password?

You could run `history` to see the last commands you entered in your shell and also check the content of your `.env` file. Maybe you can find the problem.

I guess you created those file by accident while using nano (didn't read the output of nano and entered your password while nano just wanted the name of the newly created file).

I don't know what you do did - and so you. But I think we both agree, that this is not an Klipper-Backup issue but a Linux-newbie one.
