### ISSUE TITLE
Security issue - telegram bot conf

### ISSUE THREAD

**Issue by LegionPleingaz** [Staubgeborener/klipper-backup#88]
### Is your feature request related to a problem? Please describe.

With the global push to a git, the bot creds are exposed.
is it possible to exclude one to x files?

### Describe the solution you'd like

Modify in the .env file

### Describe alternatives you've considered

no idea

**Comment by Tylerjet** [comment]
You don't have to have your backup repository public but you can exclude files by adding them to the exclude list in the .env

![image](https://github.com/Staubgeborener/klipper-backup/assets/12002714/05b735ae-9ec2-4666-9b5e-488359894d3b)

**Comment by Staubgeborener** [comment]
Also please read [this](https://staubgeborener.github.io/klipper-backup/configuration/#gitignore-do-not-upload-certain-files).
