### ISSUE TITLE
Add Restore Script

### ISSUE THREAD

**Issue by Salty-Doug** [Staubgeborener/klipper-backup#89]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

It would be nice to have a restore script that would restore all files.

### Describe alternatives you've considered

I am not a Github developer.

**Comment by Staubgeborener** [comment]
Is being planned and will be released shortly in some weeks/months. The current focus is on the installation script and KIAUH support.

**Comment by Salty-Doug** [comment]
Thanks for the reply.I found that the Installation went Pretty good between the video and your documentation. Fair Winds and Calm SeasSalty Doug SimmsSent from my iPhoneOn Mar 25, 2024, at 2:00 AM, Staubgeborener ***@***.***> wrote:﻿
Is being planned and will be released shortly in some weeks/months. The current focus is on the installation script and KIAUH support.
