### ISSUE TITLE
Does not back up symbolic links like those used by ERCF

### ISSUE THREAD

**Issue by jwhite** [Staubgeborener/klipper-backup#90]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the `code` more readable which helps to fix the problem

### What happened

By default, this will skip symbolic links, which is probably not the desired behavior.

Adding the -l flag to rsync will copy those.

### What did you expect to happen

My backups would be created.

### How to reproduce

Install any klipper extension that puts symbolic links into printer configuration.

**Comment by Tylerjet** [comment]
Symbolic Links are not backed up as they are read only files https://github.com/Staubgeborener/klipper-backup/issues/69#issuecomment-1965839873

**Comment by Tylerjet** [comment]
You can see it in Fluidd and mainsail denoted by the lock icon and in some of the files denoting they are read only.

![image](https://github.com/Staubgeborener/klipper-backup/assets/12002714/824621d8-e687-410c-876f-9ffe8ffb94f0)
![image](https://github.com/Staubgeborener/klipper-backup/assets/12002714/1a03a9a4-6bab-4e6f-a435-91e273eb7431)
