### ISSUE TITLE
Pushing updates doesn't work

### ISSUE THREAD

**Issue by Settordici** [Staubgeborener/klipper-backup#98]
### Code of Conduct

- [X] I promise that i have used markdown syntax to make the `code` more readable which helps to fix the problem

### What happened

I ran `~/klipper-backup/script.sh`, and it didn't push to the repository. I attached a screenshot of the terminal output

### What did you expect to happen

I expected it to push the updates

### How to reproduce

Just run `~/klipper-backup/script.sh`, but it's probably something that happened on my end

### Additional information

![image](https://github.com/Staubgeborener/klipper-backup/assets/63635493/276e38b4-237b-4db3-b3b7-01425f83989d)

**Comment by Tylerjet** [comment]
can you try removing the config backup folder and then try running script.sh again:
```
cd
rm -rf config_backup
```

also is this an existing repo or a brand new one created for use with the backup script?

**Comment by Settordici** [comment]
It worked, thank you for you quick answer.

I created the repo first, and then ran the script

**Comment by Tylerjet** [comment]
No Problem!
